language: java

jdk:
  - openjdk8

install:
  - mvn clean install -DskipTests

script:
  - mvn test
  - mvn exec:java &
  - mvn exec:java
  - cd partie
  - cd joueur
  - cd appariement
  - cd anagrammeur