language: java

jdk:
  - openjdk17

services:
  - docker

install:
  - mvn clean install -DskipTests

# before_script:
#   - docker-compose --version
#   - docker ps -a -q
#   - docker build serveur -t exempleio:serveur
#   - docker build client -t exempleio:client
#   - docker images

script:
  - mvn test
  - cd appariement
  - mvn exec:java &
  - cd ..
  - cd partie
  - mvn exec:java -Dserver.port=9090 -Dexec.args="http://localhost:8080" &
  - cd ..
  - cd anagrammeur
  - mvn exec:java -Dserver.port=9191 -Dexec.args="http://localhost:8080" &
  - cd ..
  - cd player
  - mvn exec:java -Dserver.port=9292 -Dexec.args="http://localhost:8080" 
  - cd ..