language: java

jdk:
  - openjdk17

services:
  - docker

install:
  - mvn install -DskipTests

# before_script:
#   - docker-compose --version
#   - docker ps -a -q
#   - docker build serveur -t exempleio:serveur
#   - docker build client -t exempleio:client
#   - docker images

script:
  - mvn test
  - cd partie
  - mvn exec:java
  - cd ..
  - cd joueur
  - mvn exec:java
  - cd ..
  - cd appariement
  - mvn exec:java
  - cd ..
  - cd anagrammeur
  - mvn exec:java
  - cd ..