version: '3'

services:

####################Appariement####################
  appariement:
    image: scrabble:appariement
    container_name: appariement
    networks:
      testing_net:
        ipv4_address: 172.28.0.253
    #depends_on:
      #- client

####################player####################
  joueur:
    image: scrabble:player
    # container_name: player
    environment:
      - SERVER_IP=172.28.0.253
    networks:
      testing_net:
      #  ipv4_address: 172.28.0.3

####################partie####################
  partie:
    image: scrabble:partie
    # container_name: partie
    environment:
      - SERVER_IP=172.28.0.253
    networks:
      testing_net:
      #  ipv4_address: 172.28.0.3

####################anagrammeur####################
  anagrammeur:
    image: scrabble:anagrammeur
    # container_name: anagrammeur
    environment:
      - SERVER_IP=172.28.0.253
    networks:
      testing_net:
        ipv4_address: 172.28.0.252





networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16